# Generated by Django 5.1.3 on 2024-11-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Microorganisms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('add_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'microorganisms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MicroVsPlants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.FloatField(blank=True, null=True)),
                ('concentration_sd', models.FloatField(blank=True, null=True)),
                ('concentration_se', models.FloatField(blank=True, null=True)),
                ('concentration_units', models.CharField(blank=True, max_length=255, null=True)),
                ('repetitions', models.IntegerField(blank=True, null=True)),
                ('experiment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('original_value', models.CharField(blank=True, max_length=63, null=True)),
                ('sd', models.FloatField(blank=True, null=True)),
                ('se', models.FloatField(blank=True, null=True)),
                ('units', models.CharField(blank=True, max_length=255, null=True)),
                ('interpretation_value', models.FloatField(blank=True, null=True)),
                ('add_info', models.TextField(blank=True, null=True)),
                ('method_name', models.CharField(blank=True, max_length=255, null=True)),
                ('method_type', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'micro_vs_plants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('part', models.CharField(blank=True, max_length=63, null=True)),
                ('origin', models.TextField(blank=True, null=True)),
                ('add_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('authors', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_year', models.SmallIntegerField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'publications',
                'managed': False,
            },
        ),
    ]
